tasks:
  - name: Run Ozone FOSS
    init: scripts/mvnw clean package
  - command: source target/go-to-scripts-dir.sh && ./start-demo.sh 1.0.0-alpha.12 # Replace by the version of your choice
ports:
  - name: OpenMRS
    description: OpenMRS 3
    port: 80
    onOpen: open-browser
  - name: Odoo
    description: Odoo
    port: 8069
  - name: SENAITE
    description: SENAITE
    port: 8081
