services:

  eip-hcwathome-openmrs:
    image: mekomsolutions/eip-client
    environment:
      OPENMRS_BASE_URL: http://openmrs:8080/openmrs
      OPENMRS_USERNAME: ${OPENMRS_USER}
      OPENMRS_PASSWORD: ${OPENMRS_PASSWORD}
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST}
      OPENMRS_DB_PORT: ${OPENMRS_DB_PORT}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME}
      OPENMRS_DB_USER: ${OPENMRS_DB_USER}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD}
      #OAUTH_ENABLED: false
      EIP_DB_NAME: ${EIP_HCW_DB_NAME}
      EIP_DB_USER: ${EIP_HCW_DB_USER}
      EIP_DB_PASSWORD: ${EIP_HCW_DB_PASSWORD}
      EIP_DEBEZIUM_SERVER_ID: ${EIP_HCW_DEBEZIUM_SERVER_ID}
      EIP_DEBEZIUM_SERVER_NAME: eip_hcwathome_openmrs
      EIP_DEBEZIUM_USER: root
      EIP_DEBEZIUM_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #EIP_LOGBACK_FILE: /eip-client/logback.xml
      DEBEZIUM_OFFSET_FILE: /eip-client/offset.txt
      DEBEZIUM_HISTORY_FILE: /eip-client/history.txt
      HCW_AT_HOME_BACKEND_URL: ${HCW_AT_HOME_BACKEND_URL}
      HCW_AT_HOME_AUTH_TOKEN: ${HCW_AT_HOME_AUTH_TOKEN}
      OPENMRS_EMAIL_PERSON_ATTR_TYPE_UUID: ${OPENMRS_EMAIL_PERSON_ATTR_TYPE_UUID}
      OPENMRS_ENCOUNTER_TYPE_UUID: ${OPENMRS_ENCOUNTER_TYPE_UUID}
      EIP_FHIR_SERVER_URL: http://openmrs:8080/openmrs/ws/fhir2/R4
      EIP_FHIR_USERNAME: ${OPENMRS_USER}
      EIP_FHIR_PASSWORD: ${OPENMRS_PASSWORD}
      LOG_LEVEL: ${EIP_HCW_LOG_LEVEL:-INFO}
      DEBEZIUM_EVENT_READER_INITIAL_DELAY: ${EIP_HCW_DEBEZIUM_EVENT_READER_INITIAL_DELAY}
      DEBEZIUM_EVENT_READER_DELAY: ${EIP_HCW_DEBEZIUM_EVENT_READER_DELAY}
      DEBEZIUM_EVENT_RETRY_INITIAL_DELAY: ${EIP_HCW_DEBEZIUM_EVENT_RETRY_INITIAL_DELAY}
      DEBEZIUM_EVENT_RETRY_DELAY: ${EIP_HCW_DEBEZIUM_EVENT_RETRY_DELAY}
      APPOINTMENTS_TASK_INITIAL_DELAY: ${EIP_HCW_APPOINTMENTS_TASK_INITIAL_DELAY}
      APPOINTMENTS_TASK_DELAY: ${EIP_HCW_APPOINTMENTS_TASK_DELAY}
    depends_on:
      openmrs:
        condition: service_healthy
    volumes:
      - "${EIP_HCW_OPENMRS_ROUTES_PATH}:/eip-client/routes"
    networks:
      web:
      ozone:
        aliases:
          - eip-hcwathome-openmrs
  mysql:
    environment:
      EIP_DB_NAME_ODOO: ${EIP_HCW_DB_NAME}
      EIP_DB_USER_ODOO: ${EIP_HCW_DB_USER}
      EIP_DB_PASSWORD_ODOO: ${EIP_HCW_DB_PASSWORD}
    volumes:
      - "${SQL_SCRIPTS_PATH}/mysql/eip-hcwathome-openmrs:/docker-entrypoint-initdb.d/db/eip-hcwathome-openmrs"

volumes:
  mongo-data: ~
