x-network: &ozone-network "ozone"

x-default-logging: &default
  {}

x-log-config: &log-config
  <<: *default

services:

  bahmni-config:
    image: bahmni/standard-config:1.0.0
    volumes:
      - '${BAHMNI_CONFIG_VOLUME:?}:/usr/local/bahmni_config'
      - '${BAHMNI_CONFIG_OVERRIDE_PATH:-bahmni-config-override}:/usr/local/bahmni_config_override'
    logging: *log-config
    restart: unless-stopped
    networks:
      - ozone
    command: ["sh", "-c", "rm -rf /etc/bahmni_config/masterdata/configuration && cp -r /usr/local/bahmni_config_override/frontend/* /etc/bahmni_config/openmrs && ./start.sh"]

  openmrs:
    image: bahmni/openmrs:1.1.1
    environment:
      TZ: ${TIMEZONE}
      OMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OMRS_DB_HOSTNAME: ${OPENMRS_DB_HOST:?}
      OMRS_DB_USERNAME: ${OPENMRS_DB_USER:?}
      OMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      OMRS_CREATE_TABLES: ${OPENMRS_DB_CREATE_TABLES}
      OMRS_AUTO_UPDATE_DATABASE: ${OPENMRS_DB_AUTO_UPDATE}
      OMRS_MODULE_WEB_ADMIN: ${OPENMRS_MODULE_WEB_ADMIN}
      # OMRS_DEV_DEBUG_PORT: ${OMRS_DEV_DEBUG_PORT}
      OMRS_JAVA_SERVER_OPTS: ${OMRS_JAVA_SERVER_OPTS}
      OMRS_JAVA_MEMORY_OPTS: ${OMRS_JAVA_MEMORY_OPTS}
      SEND_MAIL: ${SEND_MAIL}
      MAIL_TRANSPORT_PROTOCOL: ${MAIL_TRANSPORT_PROTOCOL}
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST}
      MAIL_SMTP_PORT: ${MAIL_SMTP_PORT}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS_ENABLE: ${MAIL_SMTP_STARTTLS_ENABLE}
      MAIL_SMTP_SSL_ENABLE: ${MAIL_SMTP_SSL_ENABLE}
      MAIL_DEBUG: ${MAIL_DEBUG}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OMRS_DOCKER_ENV: ${OPENMRS_DOCKER_ENV}
      OMRS_C3P0_MAX_SIZE: ${OMRS_C3P0_MAX_SIZE}
      WEIGHT_CONCEPT_UUID: ${WEIGHT_CONCEPT_UUID}
      HEIGHT_CONCEPT_UUID: ${HEIGHT_CONCEPT_UUID}
      OMRS_DB_EXTRA_ARGS: ${OMRS_DB_EXTRA_ARGS}
      LUCENE_MATCH_TYPE: ${LUCENE_MATCH_TYPE}
      DOCUMENT_MAX_SIZE_MB: ${DOCUMENT_MAX_SIZE_MB}
    #ports:
      # - ${OMRS_DEV_DEBUG_PORT}:${OMRS_DEV_DEBUG_PORT}
    volumes:
      - "${BAHMNI_CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - "bahmni-lab-results:/home/bahmni/uploaded_results"
      - "bahmni-uploaded-files:/home/bahmni/uploaded-files"
      - "${BAHMNI_OPENMRS_MODULES_PATH:?}/:/openmrs/data/modules/"
      - 'bahmni-patient-images:/home/bahmni/patient_images'
      - 'bahmni-document-images:/home/bahmni/document_images'
      - 'bahmni-clinical-forms:/home/bahmni/clinical_forms'
      - "${BAHMNI_CONFIG_OVERRIDE_PATH:-openmrs-config}/initializer:/openmrs/distribution/openmrs_config/"
      - 'configuration_checksums:/openmrs/data/configuration_checksums'
      - 'sms-token:/openmrs/data/sms-token'
    depends_on:
      - mysql
    logging: *log-config
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/openmrs/index.htm" ]
      interval: 10s
      timeout: 5s
      retries: 360
      start_period: 180s
    networks:
      - *ozone-network

  # Bahmni EIP routes
  eip-bahmni:
    depends_on:
      env-substitution:
        condition: service_completed_successfully
      openmrs:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      - EIP_PROFILE=prod
      - EIP_DB_NAME_BAHMNI=${EIP_DB_NAME_BAHMNI}
      - EIP_DB_USER_BAHMNI=${EIP_DB_USER_BAHMNI}
      - EIP_DB_PASSWORD_BAHMNI=${EIP_DB_PASSWORD_BAHMNI}
      - MYSQL_ADMIN_USER=root
      - MYSQL_ADMIN_USER_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - OPENMRS_DB_HOST=${OPENMRS_DB_HOST}
      - OPENMRS_DB_PORT=${OPENMRS_DB_PORT}
      - OPENMRS_DB_NAME=${OPENMRS_DB_NAME}
      - OPENMRS_DB_USER=${OPENMRS_DB_USER}
      - OPENMRS_DB_PASSWORD=${OPENMRS_DB_PASSWORD}
      - BAHMNI_TEST_ORDER_TYPE_UUID=${EIP_TEST_ORDER_TYPE_UUID}
    image: mekomsolutions/eip-client:sha-b2f32ae
    networks:
      *ozone-network:
        aliases:
          - eip-client-bahmni
    restart: unless-stopped
    volumes:
      - "${BAHMNI_CONFIG_OVERRIDE_PATH:-bahmni-eip}/eip/routes:/routes"
      - "${BAHMNI_CONFIG_OVERRIDE_PATH:-bahmni-eip}/eip/config:/config"
      - eip-home-bahmni:/eip-home

  mysql:
    environment:
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME}
      OPENMRS_DB_USER: ${OPENMRS_DB_USER}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD}
      EIP_DB_NAME_BAHMNI: ${EIP_DB_NAME_BAHMNI}
      EIP_DB_USER_BAHMNI: ${EIP_DB_USER_BAHMNI}
      EIP_DB_PASSWORD_BAHMNI: ${EIP_DB_PASSWORD_BAHMNI}
    volumes:
      - "${SQL_SCRIPTS_PATH}/mysql/openmrs:/docker-entrypoint-initdb.d/db/openmrs"
      - "${SQL_SCRIPTS_PATH}/mysql/eip-bahmni:/docker-entrypoint-initdb.d/db/eip-bahmni"
    # command: 
    #   - "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    logging: *log-config

  bahmni-web:
    image: bahmni/bahmni-web:1.1.0
    volumes:
      - "${BAHMNI_CONFIG_VOLUME:?}:/usr/local/apache2/htdocs/bahmni_config/:ro"
    #   - "${BAHMNI_APPS_PATH:?}/ui/app/:/usr/local/apache2/htdocs/bahmni"
    #   - "${BAHMNI_APPS_PATH:?}/ui/node_modules/@bower_components/:/usr/local/apache2/htdocs/bahmni/components"
    logging: *log-config
    restart: unless-stopped
    networks:
      - *ozone-network

  implementer-interface:
    image: bahmni/implementer-interface:1.1.1
    #volumes:
    #  - "${IMPLEMENTER_INTERFACE_CODE_PATH:?}/dist:/usr/local/apache2/htdocs/implementer_interface"
    depends_on:
      - openmrs
    logging: *log-config
    restart: unless-stopped
    networks:
      - ozone

  reports:
    image: bahmni/reports:1.1.0
    environment:
      TZ: ${TIMEZONE}
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST:?}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OPENMRS_DB_USERNAME: root
      OPENMRS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
      OPENMRS_PORT: ${OPENMRS_PORT:?}
      REPORTS_DB_SERVER: reportsdb
      REPORTS_DB_NAME: ${REPORTS_DB_NAME:?}
      REPORTS_DB_USERNAME: ${REPORTS_DB_USERNAME:?}
      REPORTS_DB_PASSWORD: ${REPORTS_DB_PASSWORD:?}
      ODOO_DB_SERVER: ${POSTGRES_DB_HOST:?}
      ODOO_DB_NAME: ${ODOO_DATABASE:?}
      ODOO_DB_USERNAME: ${ODOO_DB_USER:?}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD:?}
      ICD10_LITE_INDICATOR: ${ICD10_LITE_INDICATOR}
    volumes:
      - "${BAHMNI_CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - "bahmni-queued-reports:/home/bahmni/reports"
    # - "../snomed-resources/icd10-extensions-1.0.0-SNAPSHOT.jar:/var/run/bahmni-reports/bahmni-reports/WEB-INF/lib/icd10-extensions-1.0.0-SNAPSHOT.jar:ro"
    depends_on:
      - reportsdb
      - mysql
      - bahmni-web
    logging: *log-config
    restart: unless-stopped
    networks:
      - *ozone-network

  reportsdb:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${REPORTS_DB_NAME:?}
      MYSQL_USER: ${REPORTS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${REPORTS_DB_PASSWORD:?}
    volumes:
      - 'reportsdbdata:/var/lib/mysql'
    logging: *log-config
    restart: unless-stopped
    networks:
      - *ozone-network

  patient-documents:
    image: 'bahmni/patient-documents:1.1.1'
    volumes:
      - 'bahmni-document-images:/usr/share/nginx/html/document_images'
      - 'bahmni-lab-results:/usr/share/nginx/html/uploaded_results'
      - "bahmni-uploaded-files:/usr/share/nginx/html/uploaded-files"
    environment:
      TZ: ${TIMEZONE}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
    depends_on:
      - openmrs
    logging: *log-config
    restart: unless-stopped
    networks:
      - *ozone-network

  appointments:
    image: bahmni/appointments:1.1.1
    restart: unless-stopped
    # volumes:
    # - "${APPOINTMENTS_PATH:?}/dist/:/usr/local/apache2/htdocs/appointments"
    networks:
      - *ozone-network

  sms-service:
    image: bahmni/sms-service:1.1.0
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      SMS_TOKEN: ${SMS_TOKEN}
      SMS_ORIGINATOR: ${SMS_ORIGINATOR}
      SMS_PROVIDER_API: ${SMS_PROVIDER_API}
      SMS_OPENMRS_HOST: ${OPENMRS_HOST:?}
      SMS_OPENMRS_PORT: ${OPENMRS_PORT:?}
      SMS_COUNTRY_CODE: ${SMS_COUNTRY_CODE}
    volumes:
      - 'sms-token:/opt/tokens'
    networks:
      - *ozone-network

  ipd:
    image: bahmni/microfrontend-ipd:1.0.0
    container_name: ipd
    restart: unless-stopped
    # volumes:
    #   - "${IPD_PATH:?}/dist/federation/:/usr/local/apache2/htdocs/ipd"
    logging: *log-config
    networks:
      - *ozone-network

volumes:
  eip-home-bahmni:
  openmrs-data:
  openmrsdbdata:
  bahmni-config-override: ~
  bahmni-patient-images:
  bahmni-document-images:
  bahmni-clinical-forms:
  bahmni-config:
  bahmni-lab-results:
  bahmni-uploaded-files:
  configuration_checksums:
  sms-token:
  bahmni-queued-reports:
  reportsdbdata:
