x-oauth-variables: &oauth-variables
  OAUTH_ACCESS_TOKEN_URL: ${OAUTH_ACCESS_TOKEN_URL}
  OAUTH_ENABLED: ${ENABLE_SSO}
  OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
  OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
  OAUTH_CLIENT_SCOPE: ${OAUTH_CLIENT_SCOPE}

services:

  eip-erpnext-openmrs:
    environment:
      <<: *oauth-variables
