services:

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki.yaml
    volumes:     
     - ./logging/loki-config.yaml:/etc/loki/loki.yaml
     - ${LOKI_DATA_DIR:-loki-data}:/loki
  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    depends_on:
      - loki
    volumes:
      - ${GRAFANA_DATA_DIR:-grafana-data}:/var/lib/grafana
      - ./logging/grafana/provisioning:/etc/grafana/provisioning:ro

volumes:
  grafana-data:
  loki-data:

# Promtail and Loki configs will be created in the next step.
